
# PYTHON_VERSION example
#   3.10.9
#   3.11.4

WORKDIR /usr/local

ENV PYENV_ROOT /usr/local/pyenv

RUN git clone https://github.com/pyenv/pyenv.git $PYENV_ROOT

# I don't want to use pyenv, but only ability to install any version of Python.
RUN $PYENV_ROOT/bin/pyenv install -s -v $PYTHON_VERSION

RUN $PYENV_ROOT/versions/$PYTHON_VERSION/bin/pip install --upgrade pip
RUN $PYENV_ROOT/versions/$PYTHON_VERSION/bin/pip install pipenv

ENV PATH $PYENV_ROOT/versions/$PYTHON_VERSION/bin:$PATH
