
# AWSCLI_VERSION example
#   2.13.0

WORKDIR /usr/local

RUN curl -SsfLk "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWSCLI_VERSION}.zip" -o awscli-exe-linux-x86_64.zip
RUN unzip awscli-exe-linux-x86_64.zip
RUN ./aws/install --bin-dir /usr/local/aws/bin/

ENV PATH /usr/local/aws/bin:$PATH

