
# SBT_VERSION example
#   1.9.0
# https://github.com/sbt/sbt/releases

WORKDIR /usr/local

ARG SBT_URL="https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.zip"
RUN curl -SsfLk ${SBT_URL} -o sbt.zip
RUN mkdir tmp
RUN unzip sbt.zip -d tmp
RUN mv tmp/$(ls tmp) sbt
RUN rmdir tmp

RUN mkdir /tmp/.sbt/
RUN chmod -R 777 /tmp/.sbt/

ENV PATH /usr/local/sbt/bin:$PATH

