
# SCALA_VERSION example
#   3.1.3
#   3.3.0
# https://www.scala-lang.org/download/all.html

WORKDIR /usr/local

ARG SCALA_URL="https://github.com/lampepfl/dotty/releases/download/${SCALA_VERSION}/scala3-${SCALA_VERSION}.tar.gz"
RUN curl -SsfLk ${SCALA_URL} -o scala.tgz
RUN mkdir tmp
RUN tar xzf scala.tgz -C tmp
RUN mv tmp/$(ls tmp) scala
RUN rmdir tmp

ENV SCALA_HOME /usr/local/scala
ENV PATH $SCALA_HOME/bin:$PATH

