
# PYTHON_VERSION example
#   3.10.9
#   3.11.4
# https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build

RUN apt install -y \
    git \
    gcc \
    make \
    pkg-config \
    zlib1g-dev \
    libffi-dev \
    libssl-dev \
    libsqlite3-dev \
    libbz2-dev \
    libncurses5-dev \
    libreadline-dev \
    liblzma-dev \
    ;

WORKDIR /usr/local

ENV PYENV_ROOT /usr/local/pyenv

RUN git clone https://github.com/pyenv/pyenv.git $PYENV_ROOT

# I don't want to use pyenv, but only ability to install any version of Python.
RUN $PYENV_ROOT/bin/pyenv install -s -v $PYTHON_VERSION

RUN $PYENV_ROOT/versions/$PYTHON_VERSION/bin/pip install --upgrade pip
RUN $PYENV_ROOT/versions/$PYTHON_VERSION/bin/pip install pipenv

ENV PATH $PYENV_ROOT/versions/$PYTHON_VERSION/bin:$PATH
